swagger: '2.0'
info:
  title: Account API
  description: <p>"This Account API enables user to retrieve Account Balance and Transactions."</p> <p>Assumption - </p><p> 1. I am creating both the api's using HTTP POST Method because I am assuming that this API might be used as B2B. </p><p>2. For the ease of integration with customer I do not want to encrypt account number and then use it as HTTP GET query param.</p><p> The sample url for both the api's will be  --</p><p>
        - Account Balance Inquiry - http://localhost:8080/accounts/balance/inquiry </p><p>
        - Account Transactions - http://localhost:8080/accounts/transactions/inquiry </p>
  
  version: '1.0'
  termsOfService: 'http://swagger.io/terms/'
x-basePaths:
  - basePath: /accounts/
x-security:
  oneWayTLS_AppKey: false
  oneWayTLS_HMAC: true
  twoWayTLS_HMAC: false
  oAuth: false
schemes:
  - http
consumes:
  - application/json
paths:
  /balance/inquiry:
    post:
      tags:
      - "Account API"
      summary: This api help user to retrieve account balance..
      description: ''
      operationId: getAccountBalance
      produces:
        - application/json
      parameters:
        - name: transaction_id
          in: header
          description: 'A unique transaction id for troubleshooting/auditing purposes. If not provided by clients vpayment system will generate one.e.g., <code>47077162348524058998</code>'
          required: false
          type: string
          maxLength: 64
        - name: client_id
          in: header
          description: 'Authorization header generated by the Client. e.g., <code>"gChHVrxcJZUm5VkwIIDiudDBbUV6RVHqrNzs/qbWSyo="</code>'
          required: true
          type: string
        - in: body
          name: body
          description: parameters
          required: true
          schema:
            type: object
            properties:
              accountNumber:
                type: string
                description: '<p>A 16 digit accountNumber used to retrieve account balance. (Required).</p><p>e.g., <code>1236549870125463</code></p>'
                maxLength: 16
                x-required: true
      responses:
        '201':
          description: Successful operation.
          headers:
            transaction_id:
              description: '<p>A unique transaction id for troubleshooting/auditing purposes.</p><p>e.g.,<code>47077162348524058998</code></p>'
              type: string
              maxLength: 64
          schema:
            type: object
            properties:
              accountNumber:
                type: string
                description: '<p>account number.</p><p>e.g.,<code>1236549870125463</code></p>'
              balance:
                type: string
                description: '<p>current account balance</p><p>e.g.,<code>5426.32</code></p>'
        '400':
          description: <ul><li>Invalid request data. A required field is either missing or invalid.</li><li>Either Authorization Header (client_id) is null or empty.</li></ul>
        '401':
          description: Unauthorized access.
        '404':
          description: Resource not found.
        '405':
          description: Method not allowed.
        '429':
          description: Too many requests.
        '503':
          description: 'System is temporarily unavailable. Please try again. If the problem continues, please contact your local Help Desk.'
        '504':
          description: Gateway timeout.
      x-tryit:
        - name: UserDetails
          requestHeaders: 'POST http://localhost:8080/accounts/balance/inquiry HTTP/1.1 <br/>transaction_id : 47077162348524058998 client_id: "2ece6443-9de8-4f7c-99b6-5052c1f3fd61"'
          requestBody:
            accountNumber: '1236544789987888'
          responseHeaders: 'HTTP/1.1 201 OK <br/>transaction_id: 24599418917781242006 <br/>'
          responseBody:
            accountNumber: '1236544789987888'
            balance: '6542.26'
          responseCode: '200'
          responseMessage: OK
  /transactions/history:
    post:
      tags:
      - "Account API"
      summary: This API is used to retrieve account transactions history.
      description: ''
      operationId: getAccountTransactions
      produces:
        - application/json
      parameters:
        - name: transaction_id
          in: header
          description: 'A unique transaction id for troubleshooting/auditing purposes. If not provided by clients vpayment system will generate one.e.g., <code>47077162348524058998</code>'
          required: false
          type: string
          maxLength: 64
        - name: client_id
          in: header
          description: 'Authorization header generated by the Client. e.g., <code>"gChHVrxcJZUm5VkwIIDiudDBbUV6RVHqrNzs/qbWSyo="</code>'
          required: true
          type: string
        - in: body
          name: body
          description: parameters
          required: true
          schema:
            type: object
            properties:
              accountNumber:
                type: string
                description: '<p>A 16 digit accountNumber used to retrieve account balance. (Required).</p><p>e.g., <code>1236549870125463</code></p>'
                x-required: true
                maxLength: 16
              transType:
                type: string
                description: '<p>specify transactions type you would like to retrieve. </p><ul><li>Deposit</li><li>Withdraw<li>Either pass null value or do not send the field to retrieve both type of transactions. </li></ul></p><p>e.g., <code>DW</code></p>'
                x-required: false
                maxLength: 2
              transStartDate:
                type: string
                description: '<p>transactions start date. </p><ul><li> format : The most common ISO DateTime Format yyyy-MM-ddTHH:mm:ss.SSS, 2000-10-31T01:30:00.000-05:00.</li></ul></p><p>Its the date from which you want to see the transactions.</p><p>e.g., <code>2000-10-31T01:30:00.000-05:00</code></p>'
                x-required: true
                maxLength: 30  
              transEndDate:
                type: string
                description: '<p>transactions end date. </p><ul><li> format : The most common ISO DateTime Format yyyy-MM-ddTHH:mm:ss.SSS, 2000-10-31T01:30:00.000-05:00.</li></ul></p><p>Its the date till when you want to see the transactions.</p><p>e.g., <code>2000-10-31T01:30:00.000-05:00</code></p>'
                x-required: true
                maxLength: 10
      responses:
        '200':
          description: Successful operation.
          headers:
            transaction_id:
              description: '<p>A unique transaction id for troubleshooting/auditing purposes.</p><p>e.g.,<code>47077162348524058998</code></p>'
              type: string
              maxLength: 64
          schema:
            type: object
            properties: 
              status:
                type: object
                description: <p>status</p>
                properties:
                  status:
                    type: string
                    description: '<p><p>staus code.<li>0 - Transactions found and returned successfully</li><li>1 - Response was limited to first "+pageSize+" transactions</li><li>2 - Account not found</li><li>3 - No Transactions found</li></p><p>e.g., <code>0</code></p>'
                  message:
                    type: string
                    description: '<p><p>message.<li>0 - Transactions found and returned successfully</li><li>1 - Response was limited to first "+pageSize+" transactions</li><li>2 - Account not found</li><li>3 - No Transactions found</li></p><p>e.g., <code>Transactions found and returned successfully</code></p>'
              accountNumber:
                type: string
                description: '<p>A 9 digit accountNumber used to retrieve account balance.</p><p>e.g., <code>123654987</code></p>'
              transCount:
                type: string
                description: '<p>total number of transactions present for the specified timeframe. </p><ul><li>In one api call only 4 transactions will be retireved and if the transactions are more than 4 then in this field you will be able to see the total transactions count and accordingly make a decision to make single api call to retrieve more transactions.</p><p>e.g., <code>80</code></p>'
              paginationTime:
                type: string
                description: '<p>If there are more than 4 transactions in the timeframe you specific then you will get this field value in response which you can use as a start date/time to retrieve more transaction.<p>Its the date from which you want to see more transactions.</p><p>e.g., <code>2000-10-31T01:30:00.000-05:00</code></p>' 
              accountTransactions:
                type: object
                description: <p>transactions details</p>
                properties:
                  transAmount:
                    type: string
                    description: '<p><p>transaction amount.</p><p>e.g., <code>5684.68</code></p>'
                  transTime:
                    type: string
                    description: '<p>timestamp of the transaction.</p><p></p>'
                  transType:
                    type: string
                    description: '<p>specify transactions type you would like to retrieve. </p><ul><li>Deposit </li><li>Withdraw </li>type of transactions which includes deposit and withdraw.</li></ul></p><p>e.g., <code>Deposit</code></p>'
        '400':
          description: <ul><li>Invalid request data. A required field is either missing or invalid.</li><li>Either Authorization Header (client_id) is null or empty.</li></ul>
        '401':
          description: Unauthorized access.
        '404':
          description: Resource not found.
        '405':
          description: Method not allowed.
        '429':
          description: Too many requests.
        '503':
          description: 'System is temporarily unavailable. Please try again. If the problem continues, please contact your local Help Desk.'
        '504':
          description: Gateway timeout.
      x-tryit:
        - name: Issue Virtual Account
          requestHeaders: 'POST http://localhost:8080/accounts/transactions/inquiry HTTP/1.1 <br/>transaction_id : 47077162348524058998 <br/>client_id: "2ece6443-9de8-4f7c-99b6-5052c1f3fd61"'
          requestBody:
            accountNumber: '123456789'
            transType: 'Deposit'
            transStartDate: '2021-01-10T01:30:00.000-05:00'
            transEndDate: '2021-01-30T01:30:00.000-05:00'
          responseHeaders: 'HTTP/1.1 200 OK <br/>transaction_id: 24599418917781242006 <br/>'
          responseBody:
            status:
              status: 0
              message: 'Transactions found and returned successfully'
            accountNumber: '5486554852255622'
            moreTransInd: 'Y'
            transCount: '80'
            accountTransactions:
              transAmount: BILLINGID
              transTime: User
              transType: 'Deposit'
          responseCode: '200'
          responseMessage: OK